### PR TITLE
feat: vercel domains api

### PR DESCRIPTION
**Pull request by matekdev**

### CODE REVIEW

**Comment by matekdev** [comment]
Domains now create and delete when requested via the UI. The next steps would be to figure out the following...

1. The domains get created and forwarded to the production site, we need a way to handle this locally for testing purposes
2. Figure out how we want to redirect the user to the correct location

**Review by matekdev — COMMENTED** [review]
I've also added
`PROJECT_ID_VERCEL`
`TEAM_ID_VERCEL`
`AUTH_BEARER_TOKEN`

to Vercel env variables for dev, preview, and production. From my understanding, these shouldn't be leaked to the public. It also seems like the GitHub build is failing, we may need to provide these secrets there as well?

**Comment by matekdev** [comment]
Action items
1. Use admin client when fetching for `deep_link` redirection logic, remove RSL policy that allows access to everyone
2. Undo Vercel call if DB call fails
3. Check to see if user has an active session in all API calls, (401) error otherwise
4. During deletion, check to see if user can select the domain, if so, they can delete it
5. Verify all domains being passed are `*.turt.link`
6. Create a fake table to mirror the vercel API when in development `fake_dns_provider`
7. Move to a 404 page if the link is not in the database
8. Is_archived should be on both databases

**Comment by matekdev** [comment]
@MisterJimson ready to go... I did leave out the `is_archived` bit.

If a URL or dynamic_link becomes archived, should a user be able to create another instance thus updating the entry from the `is_archived` state from `true` -> `false`?

**Review by MisterJimson — APPROVED** [review]

**Comment by MisterJimson** [comment]
@matekdev we can leave it out for now. It would be used for historical tracking, support, understanding what happened.

**Pull request merged**
